[package]
name = "dlt-core"
version = "0.9.2"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"
description = """
Parser and writer for autosar DLT Diagnostic Log and Trace
"""
license-file = "LICENSE.txt"
repository = "https://github.com/esrlabs/dlt-core"

[dependencies]
byteorder = "1.4"
bytes = "1.0"
chrono = "0.4"
crossbeam-channel = "0.5"
derive_more = "0.15"
humantime = "2.1"
lazy_static = "1.4"
log = "0.4"
nom = "6.1"
pcap-parser = "0.11"
quick-xml = "0.22"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
dirs = "3.0"
env_logger = "0.8"
pretty_assertions = "0.7"
proptest = "1.0"
proptest-derive = "0.3"

[[bench]]
name = "dlt_benchmarks"
harness = false
